spring:
  datasource:
    url: jdbc:postgresql://maglev.proxy.rlwy.net:39546/railway?sslmode=require
    username: postgres
    password: McDzmajGeybGrDmnEqLZhScmuNZSsxUQ

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
